# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DemeDecompC <- function(ED, n_deme, node_indices) {
    .Call('_scoal_DemeDecompC', PACKAGE = 'scoal', ED, n_deme, node_indices)
}

Testing <- function(ED, node_indices) {
    .Call('_scoal_Testing', PACKAGE = 'scoal', ED, node_indices)
}

