# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title NodeCountC
#' @description Counts the number of migrations between pairs of demes, and coalescences within each deme
#' @param ED NumericMatrix Extended data object representing structured phylogeny
#' @param n_deme int Number of demes modelled under ED
#' @param node_indices NumericVector Vector giving row numbers in ED for node labels
#' @returns List containing matrix m with element (i,j) giving the number of migrations i -> j backwards in time, and a vector c with element i giving the number of coalescences occurring in deme i
#'
#' @export
#'
NodeCountC <- function(ED, n_deme, node_indices) {
    .Call('_scoal_NodeCountC', PACKAGE = 'scoal', ED, n_deme, node_indices)
}

#' @title NodeCountC
#' @description Counts the number of migrations between pairs of demes, and coalescences within each deme
#' @param ED NumericMatrix Extended data object representing structured phylogeny
#' @param n_deme int Number of demes modelled under ED
#' @param node_indices NumericVector Vector giving row numbers in ED for node labels
#' @returns List containing matrix m with element (i,j) giving the number of migrations i -> j backwards in time, and a vector c with element i giving the number of coalescences occurring in deme i
#'
#' @export
#'
StructuredLikelihoodC <- function(ED, eff_pop, gen_len, mig_mat, node_indices) {
    .Call('_scoal_StructuredLikelihoodC', PACKAGE = 'scoal', ED, eff_pop, gen_len, mig_mat, node_indices)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_scoal_RcppExport_registerCCallable', PACKAGE = 'scoal')
})
